# Generated by Django 5.0.4 on 2024-05-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_age_blog_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='age',
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
